version: '3'

networks:
  gnomebot:
    driver: bridge

services:
  dev:
    build: .
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    volumes:
      - './src:/app/src:ro'
      - './logs:/app/logs:rw'
    command: yarn run dev
    depends_on:
      - redis
    networks:
      - gnomebot
  gnomebot:
    build: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - './src:/app/src:ro'
      - './logs:/app/logs:rw'
    depends_on:
      - redis
    networks:
      - gnomebot
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - gnomebot
